import {
  type Icon,
  ArrowsOut,
  CalendarCheck,
  ChartBar,
  ChartLine,
  ChatTeardropText,
  CheckCircle,
  Circle,
  CircleDashed,
  Compass,
  Cube,
  Diamond,
  Drop,
  Fire,
  Flag,
  Gauge,
  GearSix,
  GridNine,
  Layout,
  ListBullets,
  MagnifyingGlass,
  MapPin,
  MapTrifold,
  Mountains,
  PaintBrush,
  Palette,
  Path,
  PencilLine,
  Polygon,
  Ruler,
  ShareNetwork,
  Sparkle,
  SquaresFour,
  Stack,
  Table,
  Target,
  WarningCircle,
  Wind,
} from "@phosphor-icons/react";

export type PhosphorIconOption = {
  name: string;
  label: string;
  Icon: Icon;
};

export const PHOSPHOR_ICON_OPTIONS: PhosphorIconOption[] = [
  { name: "MapPin", label: "Map pin", Icon: MapPin },
  { name: "Circle", label: "Circle", Icon: Circle },
  { name: "Warning", label: "Warning", Icon: WarningCircle },
  { name: "Flag", label: "Flag", Icon: Flag },
  { name: "CheckCircle", label: "Check circle", Icon: CheckCircle },
  { name: "CircleDashed", label: "Dashed circle", Icon: CircleDashed },
  { name: "Diamond", label: "Diamond", Icon: Diamond },
  { name: "Square", label: "Squares", Icon: SquaresFour },
  { name: "Cube", label: "Cube", Icon: Cube },
  { name: "Target", label: "Target", Icon: Target },
  { name: "Compass", label: "Compass", Icon: Compass },
  { name: "Map", label: "Map", Icon: MapTrifold },
  { name: "Mountains", label: "Mountains", Icon: Mountains },
  { name: "Wind", label: "Wind", Icon: Wind },
  { name: "Fire", label: "Fire", Icon: Fire },
  { name: "Drop", label: "Drop", Icon: Drop },
  { name: "ChartBar", label: "Bar chart", Icon: ChartBar },
  { name: "ChartLine", label: "Line chart", Icon: ChartLine },
  { name: "Gauge", label: "Gauge", Icon: Gauge },
  { name: "Grid", label: "Grid", Icon: GridNine },
  { name: "Table", label: "Table", Icon: Table },
  { name: "Stack", label: "Stack", Icon: Stack },
  { name: "Polygon", label: "Polygon", Icon: Polygon },
  { name: "Path", label: "Path", Icon: Path },
  { name: "ShareNetwork", label: "Network", Icon: ShareNetwork },
  { name: "ArrowsOut", label: "Expand", Icon: ArrowsOut },
  { name: "Calendar", label: "Calendar", Icon: CalendarCheck },
  { name: "Chat", label: "Chat", Icon: ChatTeardropText },
  { name: "Search", label: "Search", Icon: MagnifyingGlass },
  { name: "PaintBrush", label: "Paint brush", Icon: PaintBrush },
  { name: "Palette", label: "Palette", Icon: Palette },
  { name: "Pencil", label: "Pencil", Icon: PencilLine },
  { name: "Ruler", label: "Ruler", Icon: Ruler },
  { name: "Sparkle", label: "Sparkle", Icon: Sparkle },
  { name: "Settings", label: "Settings", Icon: GearSix },
  { name: "Layout", label: "Layout", Icon: Layout },
  { name: "List", label: "List", Icon: ListBullets },
];

export function getPhosphorIcon(name: string): Icon {
  return PHOSPHOR_ICON_OPTIONS.find((option) => option.name === name)?.Icon ?? MapPin;
}
