import {
  type Icon,
  ArrowsOut,
  ArrowsVertical,
  CalendarCheck,
  ChartBar,
  ChartBarHorizontal,
  ChartDonut,
  ChartLine,
  ChartLineUp,
  ChartScatter,
  ChatTeardropText,
  CheckCircle,
  Circle,
  CircleDashed,
  CircleHalf,
  Columns,
  Compass,
  Cube,
  Diamond,
  Drop,
  DropHalf,
  Fire,
  FlagBanner,
  Gauge,
  GearSix,
  Gradient,
  GridNine,
  Layout,
  LineSegment,
  ListBullets,
  MapPin,
  MapTrifold,
  Mountains,
  NumberSquareOne,
  PaintBrush,
  Palette,
  Path,
  PencilLine,
  Play,
  Polygon,
  PresentationChart,
  Ruler,
  ShareNetwork,
  SlidersHorizontal,
  Sparkle,
  SquaresFour,
  Stack,
  Table,
  Target,
  TextT,
  Wind,
} from "@phosphor-icons/react";

/** Phosphor icons for visualization types (picker cards, deep-dive headers, etc.). */
export const VISUAL_ICONS: Record<string, Icon> = {
  "vertical-bar": ChartBar,
  "horizontal-bar": ChartBarHorizontal,
  "line-chart": ChartLine,
  "area-chart": ChartLineUp,
  "scatter-plot": ChartScatter,
  "donut-chart": ChartDonut,
  "progress-bar": ChartBarHorizontal,
  "gauge-linear": Gauge,
  "gauge-circular": Gauge,
  "polar-wind-rose": Compass,
  range: SlidersHorizontal,
  availability: CalendarCheck,
  "kpi-card": NumberSquareOne,
  "kpi-grid": GridNine,
  table: Table,
  kpi: NumberSquareOne,
  "score-indicator": SlidersHorizontal,

  arcs: ShareNetwork,
  fences: SquaresFour,
  pillars: Columns,
  discs: Circle,
  "map-area": Polygon,
  heatmap: Fire,
  points: MapPin,
  wind: Wind,
  "map-layer": MapTrifold,
};

export function getVisualIcon(visualId: string): Icon {
  return VISUAL_ICONS[visualId] ?? ChartBar;
}

/** Phosphor icons for visual-settings subcategories in the vs-panel tab rail. */
export const SETTINGS_TAB_ICONS: Record<string, Icon> = {
  Mapping: Table,
  "Story card KPI": PresentationChart,
  "Color mode": Palette,
  "Layout & visibility": Layout,
  Legend: ListBullets,
  "Status badge": CheckCircle,
  Bar: ChartBar,
  Line: ChartLine,
  "Area styling": ChartLineUp,
  Scatter: ChartScatter,
  "Pie / Donut": ChartDonut,
  "Gauge — zone colors": CircleHalf,
  "Gauge — meter & labels": Gauge,
  "Track & marker styling": Path,
  "Intensity color ramp": Gradient,
  "Bar gradient": PaintBrush,
  "KPI card": NumberSquareOne,
  "KPI Grid": GridNine,
  Status: FlagBanner,
  "Scaling / axes": Ruler,
  Tooltips: ChatTeardropText,
  "Annotations / guidelines": PencilLine,
  "Colors & Opacity": DropHalf,
  "Line Customization": LineSegment,
  Height: ArrowsVertical,
  Size: ArrowsOut,
  "Disc Scaling": Circle,
  "Disc ring": CircleDashed,
  "Ground disc": Target,
  "Marker Shape": Diamond,
  "Marker appearance": Sparkle,
  "Heatmap Style": Fire,
  "Bin & extrusion": Stack,
  "Contour Terrain": Mountains,
  Extrusion: Cube,
  "Opacity source": Drop,
  Animation: Play,
  Advanced: GearSix,
  "Map Legend": MapTrifold,
  "Tooltip Fields": TextT,
};

export function getSettingsTabIcon(label: string): Icon {
  return SETTINGS_TAB_ICONS[label] ?? SlidersHorizontal;
}
