import {
  type Icon,
  ArrowsOut,
  ArrowsVertical,
  CalendarCheck,
  ChartBar,
  ChartBarHorizontal,
  ChartDonut,
  ChartLine,
  ChartLineUp,
  ChartScatter,
  ChatTeardropText,
  CheckCircle,
  Circle,
  CircleDashed,
  Columns,
  Compass,
  Cube,
  Diamond,
  Drop,
  Fire,
  FlagBanner,
  Gauge,
  GearSix,
  GridNine,
  Layout,
  LineSegment,
  ListBullets,
  MagnifyingGlass,
  MapPin,
  MapTrifold,
  Mountains,
  NumberSquareOne,
  PaintBrush,
  Palette,
  Path,
  PencilLine,
  Play,
  Polygon,
  PresentationChart,
  Ruler,
  ShareNetwork,
  SlidersHorizontal,
  Sparkle,
  SquaresFour,
  Stack,
  Table,
  Target,
  Wind,
} from "@phosphor-icons/react";

/** Phosphor icons for visualization types (picker cards, deep-dive headers, etc.). */
export const VISUAL_ICONS: Record<string, Icon> = {
  "vertical-bar": ChartBar,
  "horizontal-bar": ChartBarHorizontal,
  "line-chart": ChartLine,
  "area-chart": ChartLineUp,
  "scatter-plot": ChartScatter,
  "donut-chart": ChartDonut,
  "progress-bar": ChartBarHorizontal,
  "gauge-linear": Gauge,
  "gauge-circular": Gauge,
  "polar-wind-rose": Compass,
  range: SlidersHorizontal,
  availability: CalendarCheck,
  "kpi-card": NumberSquareOne,
  "kpi-grid": GridNine,
  table: Table,
  kpi: NumberSquareOne,
  "score-indicator": SlidersHorizontal,

  arcs: ShareNetwork,
  fences: SquaresFour,
  pillars: Columns,
  discs: Circle,
  "map-area": Polygon,
  heatmap: Fire,
  points: MapPin,
  wind: Wind,
  "map-layer": MapTrifold,
};

export function getVisualIcon(visualId: string): Icon {
  return VISUAL_ICONS[visualId] ?? ChartBar;
}

/** Phosphor icons for visual-settings subcategories in the vs-panel tab rail. */
export const SETTINGS_TAB_ICONS: Record<string, Icon> = {
  Mapping: Table,
  "KPI Display": PresentationChart,
  "Colors": Palette,
  Color: Palette,
  "Layout & visibility": Layout,
  Legend: ListBullets,
  "Status badge": CheckCircle,
  Bar: ChartBar,
  Line: ChartLine,
  "Area styling": ChartLineUp,
  Scatter: ChartScatter,
  "Pie / Donut": ChartDonut,
  "Meter & Labels": Gauge,
  "Track & marker styling": Path,
  "Bar gradient": PaintBrush,
  "KPI card": NumberSquareOne,
  "KPI Grid": GridNine,
  Status: FlagBanner,
  "Scaling / axes": Ruler,
  Tooltips: ChatTeardropText,
  Annotations: PencilLine,
  "Line Customization": LineSegment,
  Height: ArrowsVertical,
  Size: ArrowsOut,
  "Disc Scaling": Circle,
  "Disc ring": CircleDashed,
  "Ground disc": Target,
  "Marker Shape": Diamond,
  "Marker appearance": Sparkle,
  "Heatmap Style": Fire,
  "Bin & extrusion": Stack,
  "Contour Terrain": Mountains,
  Extrusion: Cube,
  "Opacity source": Drop,
  Animation: Play,
  "Zoom Scaling": MagnifyingGlass,
  Advanced: GearSix,
  "Map Legend": MapTrifold,
};

export function getSettingsTabIcon(label: string): Icon {
  return SETTINGS_TAB_ICONS[label] ?? SlidersHorizontal;
}
